name: Slapper
author: jojoe77777
version: 1.2.6
description: Adds entities into your world that you can slap to run commands!
main: slapper\main
api: [1.12.0]
commands:
  slapper:
    description: Create a slappable entity!
    usage: "/slapper <type> [name]"
    permission: slapper.create
  rca:
    description: Run command as another player!
    usage: "/rca <player> <command>"
    permission: slapper.rca
  nothing:
    description: Do nothing!
    usage: "/nothing"
    permission: slapper.nothing
permissions:
  slapper.create:
    description: Allow using command /slapper
    default: op
  slapper.nothing:
    description: Allow doing nothing
    default: op
  slapper.hit:
    description: Allow harming Slapper entites
    default: false
  slapper.rca:
    description: Allow running commands as other players
    default: op
  slapper.seeownskin:
    description: Allow seeing your own skin on Slapper humans
    default: false
  slapper.remove:
    description: Allow removing Slapper entities with /slapper remove
    default: op